name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/screens/images/more-1.png
    - assets/screens/images/save-instagram-2.png
    - assets/screens/images/save-instagram-1.png
    - assets/screens/images/save-instagram-2-wub.png
    - assets/screens/images/check-mark-1.png
    - assets/screens/images/user-1.png
    - assets/screens/images/save-instagram-5.png
    - assets/screens/images/save-instagram-3.png
    - assets/screens/images/user-2.png
    - assets/screens/images/check-mark-1-cFK.png
    - assets/screens/images/save-instagram-3-3Sy.png
    - assets/screens/images/files-1.png
    - assets/screens/images/save-instagram-1-tfs.png
    - assets/screens/images/save-instagram-3-fhj.png
    - assets/screens/images/save-instagram-2-aMP.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-tBj.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-jFo.png
    - assets/screens/images/save-instagram-2-H2R.png
    - assets/screens/images/more-1-EKT.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-vr5.png
    - assets/screens/images/save-instagram-6.png
    - assets/screens/images/user-1-14m.png
    - assets/screens/images/logout-1.png
    - assets/screens/images/bubble-chat-1.png
    - assets/screens/images/more-1-BpM.png
    - assets/screens/images/save-instagram-4.png
    - assets/screens/images/save-instagram-5-evD.png
    - assets/screens/images/logo.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-5yT.png
    - assets/screens/images/save-instagram-5-tcq.png
    - assets/screens/images/save-instagram-6-h6y.png
    - assets/screens/images/save-instagram-4-cQH.png
    - assets/screens/images/group-28-oy3.png
    - assets/screens/images/group-35-fkM.png
    - assets/screens/images/group-30.png
    - assets/screens/images/save-instagram-5-GSm.png
    - assets/screens/images/group-34.png
    - assets/screens/images/group-31.png
    - assets/screens/images/user-2-rt9.png
    - assets/screens/images/group-34-9MT.png
    - assets/screens/images/group-32.png
    - assets/screens/images/group-33.png
    - assets/screens/images/group-28.png
    - assets/screens/images/icon.png
    - assets/screens/images/user-2-aRP.png
    - assets/screens/images/icon-96H.png
    - assets/screens/images/setting-1.png
    - assets/screens/images/group-31-3Db.png
    - assets/screens/images/save-instagram-1-D7P.png
    - assets/screens/images/save-instagram-3-fUV.png
    - assets/screens/images/user-2-z81.png
    - assets/screens/images/save-instagram-3-4N5.png
    - assets/screens/images/save-instagram-4-cZw.png
    - assets/screens/images/save-instagram-5-Vsw.png
    - assets/screens/images/group-34-qB7.png
    - assets/screens/images/group-39.png
    - assets/screens/images/icon-bRB.png
    - assets/screens/images/save-instagram-2-Xay.png
    - assets/screens/images/group-35.png
    - assets/screens/images/icon-zss.png
    - assets/screens/images/save-instagram-6-X2Z.png
    - assets/screens/images/group-35-gg9.png
    - assets/screens/images/save-instagram-1-pho.png
    - assets/screens/images/icon-bTf.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-8iV.png
    - assets/screens/images/close-1.png
    - assets/screens/images/group-32-3ff.png
    - assets/screens/images/save-instagram-4-k1X.png
    - assets/screens/images/icon-GY9.png
    - assets/screens/images/close-2.png
    - assets/screens/images/icon-769.png
    - assets/screens/images/group-30-bWy.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-uGm.png
    - assets/screens/images/group-32-x7s.png
    - assets/screens/images/home-1.png
    - assets/screens/images/logo-yA1.png
    - assets/screens/images/more-1-vSV.png
    - assets/screens/images/group-30-Fxu.png
    - assets/screens/images/save-instagram-4-PYd.png
    - assets/screens/images/group-33-wa9.png
    - assets/screens/images/save-instagram-1-4WD.png
    - assets/screens/images/icon-kyw.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-h8V.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-8qP.png
    - assets/screens/images/group-30-beR.png
    - assets/screens/images/icon-A2d.png
    - assets/screens/images/group-32-tTj.png
    - assets/screens/images/group-34-e7T.png
    - assets/screens/images/user-2-noK.png
    - assets/screens/images/logo-Qp1.png
    - assets/screens/images/logo-jtD.png
    - assets/screens/images/group-35-ptH.png
    - assets/screens/images/user-2-Los.png
    - assets/screens/images/icon-3N9.png
    - assets/screens/images/group-34-z4y.png
    - assets/screens/images/group-32-gCh.png
    - assets/screens/images/more-1-zsb.png
    - assets/screens/images/logo-ZE9.png
    - assets/screens/images/group-35-wbP.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-W8Z.png
    - assets/screens/images/group-33-JE5.png
    - assets/screens/images/save-instagram-4-Xm3.png
    - assets/screens/images/logo-ZmT.png
    - assets/screens/images/group-35-jUM.png
    - assets/screens/images/save-instagram-2-LH7.png
    - assets/screens/images/group-32-Uu7.png
    - assets/screens/images/group-33-nsB.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-Msf.png
    - assets/screens/images/save-instagram-1-mbo.png
    - assets/screens/images/user-2-Aam.png
    - assets/screens/images/group-23.png
    - assets/screens/images/group-33-EaM.png
    - assets/screens/images/save-instagram-3-NgH.png
    - assets/screens/images/group-30-H6q.png
    - assets/screens/images/group-34-Kjf.png
    - assets/screens/images/group-33-USd.png
    - assets/screens/images/group-31-4Fj.png
    - assets/screens/images/save-instagram-6-WHf.png
    - assets/screens/images/group-31-zhF.png
    - assets/screens/images/group-31-bDb.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-qNR.png
    - assets/screens/images/group-31-vjj.png
    - assets/screens/images/group-32-rWM.png
    - assets/screens/images/group-30-65F.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-3R3.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-1Aq.png
    - assets/screens/images/group-33-B8V.png
    - assets/screens/images/group-31-XCM.png
    - assets/screens/images/group-35-d8u.png
    - assets/screens/images/group-30-8zm.png
    - assets/screens/images/save-instagram-4-YRX.png
    - assets/screens/images/icon-2js.png
    - assets/screens/images/icon-MGM.png
    - assets/screens/images/save-instagram-5-W4h.png
    - assets/screens/images/group-42.png
    - assets/screens/images/more-1-AQ9.png
    - assets/screens/images/icon-Qho.png
    - assets/screens/images/group-42-nEV.png
    - assets/screens/images/icon-9Kw.png
    - assets/screens/images/more-1-7hK.png
    - assets/screens/images/user-2-gE5.png
    - assets/screens/images/save-instagram-3-RWy.png
    - assets/screens/images/group-42-qY5.png
    - assets/screens/images/group-35-bgD.png
    - assets/screens/images/group-30-Rah.png
    - assets/screens/images/user-2-xuP.png
    - assets/screens/images/home-1-4Yy.png
    - assets/screens/images/group-33-R45.png
    - assets/screens/images/group-34-ZRB.png
    - assets/screens/images/group-32-MS9.png
    - assets/screens/images/icon-odj.png
    - assets/screens/images/icon-EVo.png
    - assets/screens/images/setting-1-E33.png
    - assets/screens/images/camera-1.png
    - assets/screens/images/logo-axR.png
    - assets/screens/images/user-2-q4M.png
    - assets/screens/images/user-2-WTs.png
    - assets/screens/images/save-instagram-4-ZCu.png
    - assets/screens/images/save-instagram-1-7jX.png
    - assets/screens/images/image-3.png
    - assets/screens/images/group-31-nZF.png
    - assets/screens/images/user-2-btd.png
    - assets/screens/images/thumbs-up-1.png
    - assets/screens/images/save-instagram-2-jvq.png
    - assets/screens/images/icon-pxh.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-buj.png
    - assets/screens/images/save-instagram-6-3cV.png
    - assets/screens/images/group-34-Eiu.png
    - assets/screens/images/user-2-Bu3.png
    - assets/screens/images/thumbs-up-1-T5s.png
    - assets/screens/images/icon-Daq.png
    - assets/screens/images/thumbs-up-1-pTT.png
    - assets/screens/images/star-6.png
    - assets/screens/images/icon-QCh.png
    - assets/screens/images/user-2-2NV.png
    - assets/screens/images/icon-uSH.png
    - assets/screens/images/image-1.png
    - assets/screens/images/icon-BJ9.png
    - assets/screens/images/logo-9Ey.png
    - assets/screens/images/logo-23s.png
    - assets/screens/images/icon-m9s.png
    - assets/screens/images/icon-Zfw.png
    - assets/screens/images/untitleddesign-removebg-preview-1.png
    - assets/screens/images/logo-fvR.png
    - assets/screens/images/logo-9sX.png
    - assets/screens/images/untitleddesign-removebg-preview-1-1.png
    - assets/screens/images/bubble-chat-1-9VB.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-4hX.png
    - assets/screens/images/save-instagram-2-QYR.png
    - assets/screens/images/food-donation-1.png
    - assets/screens/images/logo-D77.png
    - assets/screens/images/save-instagram-1-MsP.png
    - assets/screens/images/save-instagram-1-1.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-KEy.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-4TT.png
    - assets/screens/images/logout-1-QsK.png
    - assets/screens/images/arrow-down-sign-to-navigate-1-1-g73.png
    - assets/screens/images/more-1-Yqw.png
    - assets/screens/images/icon-ksK.png
    - assets/screens/images/icon-Hkm.png
    - assets/screens/images/icon-ZRK.png
    - assets/screens/images/icon-zSD.png
    - assets/screens/images/save-instagram-3-Jvu.png
    - assets/screens/images/icon-MhT.png
    - assets/screens/images/icon-JJD.png
    - assets/screens/images/icon-42V.png
    - assets/screens/images/icon-swX.png
    - assets/screens/images/image-2.png
    - assets/screens/images/close-1-Jo3.png
    - assets/screens/images/icon-s3f.png
    - assets/screens/images/icon-9qb.png
    - assets/screens/images/icon-8oT.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
