// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3VKe7Z4tfWuNYP1S-00dKdld146VQ20A',
    appId: '1:597463064109:web:590284afba7b429ebc22a4',
    messagingSenderId: '597463064109',
    projectId: 'flutterflies-332b3',
    authDomain: 'flutterflies-332b3.firebaseapp.com',
    storageBucket: 'flutterflies-332b3.appspot.com',
    measurementId: 'G-QRLH6Z2ZQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgfWzN94jU_ne5-LNd2JrNZAquecyqEPQ',
    appId: '1:597463064109:android:8ce0256707914301bc22a4',
    messagingSenderId: '597463064109',
    projectId: 'flutterflies-332b3',
    storageBucket: 'flutterflies-332b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7CSDVaGhx3NsEYiNLQrz7P4eTsgz24CU',
    appId: '1:597463064109:ios:6026ef3ec66eb8bfbc22a4',
    messagingSenderId: '597463064109',
    projectId: 'flutterflies-332b3',
    storageBucket: 'flutterflies-332b3.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7CSDVaGhx3NsEYiNLQrz7P4eTsgz24CU',
    appId: '1:597463064109:ios:635252b78c85c1d8bc22a4',
    messagingSenderId: '597463064109',
    projectId: 'flutterflies-332b3',
    storageBucket: 'flutterflies-332b3.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
